# Generated by Django 4.2 on 2025-01-30 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mouvement',
            options={},
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='type',
        ),
        migrations.AddField(
            model_name='mouvement',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scuelo.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='date_paye',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('from_cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='cash.cashier')),
                ('to_cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='cash.cashier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scuelo.anneescolaire')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.cashier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mouvement',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.cashier'),
        ),
    ]
