# Generated by Django 4.2 on 2025-02-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_cashier_alter_mouvement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='modified',
        ),
    ]
