# Generated by Django 4.2 on 2025-02-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_remove_cashier_created_remove_cashier_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='legacy_id',
            field=models.CharField(default='', max_length=36, unique=True),
        ),
    ]
