# Generated by Django 4.2 on 2025-02-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_cashier_created_cashier_modified_expense_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='modified',
        ),
        migrations.AlterField(
            model_name='tarif',
            name='causal',
            field=models.CharField(choices=[('INS', 'Inscription'), ('SCO', 'SCO'), ('TEN', 'Tenue'), ('CAN', 'Cantine')], db_index=True, max_length=5),
        ),
    ]
