# Generated by Django 4.2 on 2025-02-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anneescolaire',
            name='created',
        ),
        migrations.RemoveField(
            model_name='anneescolaire',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='created',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='created',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='created',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='typeclasse',
            name='created',
        ),
        migrations.RemoveField(
            model_name='typeclasse',
            name='modified',
        ),
    ]
