# Generated by Django 4.2.16 on 2024-11-14 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_remove_mouvement_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('C', 'CS'), ('E', 'EXTRA'), ('P', 'PY'), ('A', 'ACC'), ('B', 'BRAVO')], max_length=2)),
                ('quantity', models.PositiveIntegerField(default=2)),
                ('cost_per_uniform', models.DecimalField(decimal_places=2, help_text='Cost of each uniform', max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='reserved', max_length=10)),
                ('date_reserved', models.DateField(default=django.utils.timezone.now)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_reservations', to='scuelo.anneescolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_reservations', to='scuelo.eleve')),
            ],
        ),
    ]
