# Generated by Django 4.2.16 on 2024-11-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_uniformreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformreservation',
            name='student_type',
            field=models.CharField(choices=[('C', 'CS'), ('E', 'EXTRA'), ('P', 'PY'), ('A', 'ACC'), ('B', 'BRAVO')], editable=False, max_length=2),
        ),
    ]
