# Generated by Django 4.2 on 2025-02-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_anneescolaire_created_anneescolaire_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='hand',
            field=models.CharField(blank=True, choices=[('DA', 'DA'), ('DM', 'DM'), ('DL', 'DL'), ('DV', 'DV'), ('DP', 'DP'), ('TL', 'TL')], max_length=2, null=True),
        ),
    ]
