# Generated by Django 4.2.16 on 2024-11-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0004_alter_uniformreservation_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='scuelo.eleve'),
        ),
    ]
